### ISSUE TITLE
Doesnt seem to work in PHP7

### ISSUE THREAD

**Issue by websecnl** [Xyl2k/Cookie-stealer#5]
Willing to pay for an update :)

**Comment by Xyl2k** [comment]
i just tested on localhost and it work on php7 and even php v8.1

**Comment by websecnl** [comment]
Weird, I am getting Forbidden message. even after giving the files 777 permission.

**Comment by Xyl2k** [comment]
yes this is normal behavior, now go look into your admin.php and logs should be there.

**Comment by Xyl2k** [comment]
hmm if you mean that the httpd is returning a 401 Forbidden error, can you investigate your apache and php access log?

**Comment by Xyl2k** [comment]
`::1 - - [29/Jun/2022:18:41:13 +0200] "GET /Cookie-stealer/c.php?c=test HTTP/1.1" 200 19
::1 - - [29/Jun/2022:18:41:17 +0200] "GET /Cookie-stealer/admin.php HTTP/1.1" 200 2702
::1 - - [29/Jun/2022:18:41:21 +0200] "POST /Cookie-stealer/admin.php HTTP/1.1" 200 1957`
no prob for me, apache v2.4.5.1, php v8.1.0

**Comment by websecnl** [comment]
Yea you are right, turned out it was a misconfigured .htaccess file (Sorry to have bothered you with this)  🤦‍♂️
