### ISSUE TITLE
Your tool grabs only user agent 

### ISSUE THREAD

**Issue by anonymouss234** [Xyl2k/Cookie-stealer#9]
I am not a loser. Your tool doesn’t grab any cookies, it  grabs only  user agent, no cookie grab.  I have tool that grabs cookie perfectly. I only wanted to check yours and it poor tool. It only grabs user agents. Or are user agent cookies to you ? Dude ? Upload better php  cookies grabber bro

**Comment by Xyl2k** [comment]
blah blah blah
